services:
  - type: web
    name: dsa-questions-manager
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.5
      - key: SESSION_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: dsa-questions-db
          property: connectionString

databases:
  - name: dsa-questions-db
    databaseName: dsa_questions
    user: dsa_user